version: "3"

services:
  client:
    build:
      dockerfile: Dockerfile.dev
    image: all-in-docker_client-dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    command: ["npm", "start"]
  
  api:
    image: all-in-docker_api-dev
    ports:
      - "9229:9229"
    volumes:
      - ./api:/api
      - /api/node_modules
    command: ["sh", "wait.sh", "mongodb:27017", "npm", "start"]

networks:
  webappnetwork:
    driver: bridge