version: "3"

services:
  client:
    build:
      dockerfile: Dockerfile.prod
    image: all-in-docker_client-prod
    restart: always
    ports:
      - "8080:8080"
    command: ["hs"]
  
  api:
    build:
      args:
        - node_env=product
    image: all-in-docker_api-prod
    restart: always
    command: ["sh", "wait.sh", "mongodb:27017", "npm", "run", "start:prod" ]

  mongodb:
    restart: always

networks:
  webappnetwork:
    driver: bridge